"""nox configuration for Gafaelfawr."""

from __future__ import annotations

import logging
import os
import shutil
import sys
from collections import defaultdict
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Self

import nox
from nox.command import CommandFailed
from nox_uv import session
from testcontainers.postgres import PostgresContainer
from testcontainers.redis import RedisContainer

# Default sessions.
nox.options.sessions = ["lint", "typing", "test", "docs"]

# Other nox defaults.
nox.options.default_venv_backend = "uv"
nox.options.reuse_existing_virtualenvs = True

# Recurse into these subdirectories, which have their own separate noxfile.py.
_SUBDIRECTORIES = ["client"]


@dataclass
class _Containers:
    """Information about the started containers."""

    env: dict[str, str]
    """Additional Gafaelfawr environment variables to set."""

    postgres: PostgresContainer
    """testcontainers PostgreSQL container object."""


@contextmanager
def _start_containers() -> Iterator[_Containers]:
    """Start the containers needed to run Alembic.

    Yields
    ------
    dict of str
        Environment variables to set when running Alembic, required to load
        the Gafaelfawr configuration.
    """
    alembic_path = Path(__file__).parent / "alembic.ini"
    config_path = Path(__file__).parent / "alembic" / "gafaelfawr.yaml"
    env = {
        "GAFAELFAWR_ALEMBIC_CONFIG_PATH": str(alembic_path),
        "GAFAELFAWR_CONFIG_PATH": str(config_path),
    }

    # testcontainers is annoyingly verbose by default because nox enables
    # debug logging.
    logging.getLogger("docker").setLevel(logging.INFO)
    logging.getLogger("testcontainers").setLevel(logging.INFO)
    logging.getLogger("urllib3").setLevel(logging.INFO)

    # Start the containers and flesh out env with the additional required
    # Gafaelfawr settings. Ideally we wouldn't require Redis.
    with RedisContainer() as redis:
        redis_host = redis.get_container_host_ip()
        redis_port = redis.get_exposed_port(redis.port)
        redis_url = f"redis://{redis_host}:{redis_port}"
        env["GAFAELFAWR_REDIS_EPHEMERAL_URL"] = f"{redis_url}/1"
        env["GAFAELFAWR_REDIS_PERSISTENT_URL"] = f"{redis_url}/0"

        with PostgresContainer(
            driver="asyncpg",
            dbname="gafaelfawr",
            username="gafaelfawr",
            password=os.urandom(16).hex(),
        ) as postgres:
            print("DBNAME", postgres.dbname)
            print("URL", postgres.get_connection_url())
            env["GAFAELFAWR_DATABASE_PASSWORD"] = postgres.password
            env["GAFAELFAWR_DATABASE_URL"] = postgres.get_connection_url()
            yield _Containers(env=env, postgres=postgres)


@session(name="create-migration", uv_groups=["dev"])
def create_migration(session: nox.Session) -> None:
    """Create a database schema migration to the current schema."""
    message = session.posargs[0] if session.posargs else "Autogenerated"
    with _start_containers() as containers:
        session.run("alembic", "upgrade", "head", env=containers.env)
        session.run(
            "alembic",
            "revision",
            "--autogenerate",
            "-m",
            message,
            env=containers.env,
        )


@session(name="coverage-report", uv_groups=["dev"])
def coverage_report(session: nox.Session) -> None:
    """Generate a code coverage report from the test suite."""
    session.run("coverage", "report", *session.posargs)


@session(uv_groups=["dev", "docs"])
def docs(session: nox.Session) -> None:
    """Build the documentation."""
    doctree_dir = (session.cache_dir / "doctrees").absolute()
    with session.chdir("docs"):
        session.run(
            "sphinx-build",
            "-W",
            "--keep-going",
            "-n",
            "-T",
            "-b",
            "html",
            "-d",
            str(doctree_dir),
            ".",
            "./_build/html",
        )


@session(name="docs-clean", uv_groups=["dev", "docs"])
def docs_clean(session: nox.Session) -> None:
    """Build the documentation without any cache."""
    if Path("docs/_build").exists():
        shutil.rmtree("docs/_build")
    if Path("docs/dev/internals").exists():
        shutil.rmtree("docs/dev/internals")
    docs(session)


@session(name="docs-linkcheck", uv_groups=["dev", "docs"])
def docs_linkcheck(session: nox.Session) -> None:
    """Check links in the documentation."""
    doctree_dir = (session.cache_dir / "doctrees").absolute()
    with session.chdir("docs"):
        try:
            session.run(
                "sphinx-build",
                "-W",
                "--keep-going",
                "-n",
                "-T",
                "-b",
                "linkcheck",
                "-d",
                str(doctree_dir),
                ".",
                "./_build/linkcheck",
            )
        except CommandFailed:
            output_path = Path("_build") / "linkcheck" / "output.txt"
            if output_path.exists():
                sys.stdout.write(output_path.read_text())
            session.error("Link check reported errors")


@session(name="dump-schema", uv_groups=["dev"])
def dump_schema(session: nox.Session) -> None:
    """Create a database schema migration to the current schema."""
    with _start_containers() as containers:
        session.run("gafaelfawr", "init", env=containers.env)
        command = [
            "pg_dump",
            "-U",
            containers.postgres.username,
            containers.postgres.dbname,
        ]
        exit_code, output = containers.postgres.exec(command)
        if exit_code != 0:
            session.error(f"pg_dump failed with exit code {exit_code}")
        sys.stdout.write(output.decode())


@session(uv_only_groups=["lint"], uv_no_install_project=True)
def lint(session: nox.Session) -> None:
    """Run pre-commit hooks."""
    session.run("pre-commit", "run", "--all-files", *session.posargs)


@dataclass
class TestArguments:
    """Holds parsed test arguments, used to control test recursion.

    If the user passed in arguments to the session, they may be specific tests
    to run. In that case, only run tests in the relevant directory. This
    requires some unfortunately complicated argument parsing to separate out
    the generic arguments, any tests specific to the parent directory, and any
    tests specific to subdirectories. This class handles that parsing.
    """

    generic: list[str]
    """Arguments that don't limit execution and are always used."""

    per_directory: dict[str, list[str]]
    """Arguments that apply to only one subdirectory."""

    parent_tests: list[str]
    """Specific tests to run only in the parent directory."""

    @classmethod
    def from_session(cls, session: nox.Session) -> Self:
        """Parse the session arguments into this data structure."""
        generic = []
        per_directory: dict[str, list[str]] = defaultdict(list)
        parent_tests = []

        # Parse the session arguments.
        for arg in session.posargs:
            # Ignore a speficied test when testing if the file exists.
            test_file = arg.split("::")[0]
            if "tests/" in arg and Path(test_file).exists():
                if arg.startswith("tests/"):
                    parent_tests.append(arg)
                else:
                    found = False
                    for subdir in _SUBDIRECTORIES:
                        prefix = f"{subdir}/"
                        if arg.startswith(f"{prefix}tests"):
                            adjusted_arg = arg.removeprefix(prefix)
                            per_directory[subdir].append(adjusted_arg)
                            found = True
                            break
                    if not found:
                        generic.append(arg)
            else:
                generic.append(arg)

        # Return the results.
        return cls(
            generic=generic,
            per_directory=per_directory,
            parent_tests=parent_tests,
        )

    @property
    def run_all_tests(self) -> bool:
        """Return whether all tests are being run."""
        return not any(self.parent_tests + list(self.per_directory.values()))


@session(uv_groups=["dev", "nox"])
def test(session: nox.Session) -> None:
    """Test both the server and the client."""
    args = TestArguments.from_session(session)

    # Run in the parent dir if a parent dir test was specified, or if no tests
    # were specified.
    if args.parent_tests or args.run_all_tests:
        session.run("pytest", *args.generic, *args.parent_tests)

    # Run in a subdirectory if a test in that subdirectory was specified, or
    # if no tests were specified.
    for subdir in _SUBDIRECTORIES:
        subdir_tests = args.per_directory[subdir]
        if subdir_tests or args.run_all_tests:
            with session.chdir(subdir):
                session.run(
                    "nox", "-s", "test", "--", *args.generic, *subdir_tests
                )


@session(name="test-coverage", uv_groups=["dev", "nox"])
def test_coverage(session: nox.Session) -> None:
    """Test both the server and the client with coverage analysis."""
    args = TestArguments.from_session(session)

    # Run in the parent dir if a parent dir test was specified, or if no tests
    # were specified.
    if args.parent_tests or args.run_all_tests:
        session.run(
            "pytest",
            "--cov=gafaelfawr",
            "--cov-branch",
            "--cov-report=",
            *args.generic,
            *args.parent_tests,
        )

    # Run in a subdirectory if a test in that subdirectory was specified, or
    # if no tests were specified.
    for subdir in _SUBDIRECTORIES:
        subdir_tests = args.per_directory[subdir]
        if subdir_tests or args.run_all_tests:
            with session.chdir(subdir):
                session.run(
                    "nox",
                    "-s",
                    "test-coverage",
                    "--",
                    *args.generic,
                    *subdir_tests,
                )


@session(name="test-full", uv_groups=["dev", "nox"])
def test_full(session: nox.Session) -> None:
    """Test with a real Kubernetes server (DANGEROUS)."""
    args = TestArguments.from_session(session)

    # Run in the parent dir if a parent dir test was specified, or if no tests
    # were specified.
    if args.parent_tests or args.run_all_tests:
        session.run(
            "pytest",
            "--cov=gafaelfawr",
            "--cov-branch",
            "--cov-report=",
            *args.generic,
            *args.parent_tests,
            env={"TEST_KUBERNETES": "1"},
        )

    # Run in a subdirectory if a test in that subdirectory was specified, or
    # if no tests were specified.
    for subdir in _SUBDIRECTORIES:
        subdir_tests = args.per_directory[subdir]
        if subdir_tests or args.run_all_tests:
            with session.chdir(subdir):
                session.run(
                    "nox",
                    "-s",
                    "test-coverage",
                    "--",
                    *args.generic,
                    *subdir_tests,
                )


@session(uv_groups=["dev", "nox", "typing"])
def typing(session: nox.Session) -> None:
    """Run mypy."""
    session.run(
        "mypy",
        *session.posargs,
        "noxfile.py",
        "src",
        "tests",
    )
    session.run(
        "mypy",
        *session.posargs,
        "--namespace-packages",
        "--explicit-package-bases",
        "client/noxfile.py",
        "client/src",
        "client/tests",
        env={"MYPYPATH": "client/src"},
    )
