apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
type: Opaque
data:
  oauth2_proxy_client_secret: "{{ OAUTH2_PROXY_CLIENT_SECRET_B64 }}"
  oauth2_proxy_cookie_secret: "{{ OAUTH2_PROXY_COOKIE_SECRET_B64 }}"
