"""Remove the admin and admin_history tables

Revision ID: 613640641b2f
Revises: 5a54e4db3cf4
Create Date: 2026-08-20 00:12:57.133992+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "613640641b2f"
down_revision: str | None = "5a54e4db3cf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("admin_history_by_time"), table_name="admin_history")
    op.drop_table("admin_history")
    op.drop_table("admin")
    bind = op.get_bind()
    postgresql.ENUM(name="adminchange").drop(bind, checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("username", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("username", name=op.f("admin_pkey")),
    )
    op.create_table(
        "admin_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "action",
            postgresql.ENUM("add", "remove", name="adminchange"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("actor", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "event_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("admin_history_pkey")),
    )
    op.create_index(
        op.f("admin_history_by_time"),
        "admin_history",
        ["event_time", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
