"""Add OpenID Connect client table

Revision ID: 20ccaa8eedfd
Revises: 2feb306dd1ee
Create Date: 2026-08-18 17:31:08.216187+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20ccaa8eedfd"
down_revision: str | None = "2feb306dd1ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oidc_client",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret_hash", sa.LargeBinary(), nullable=False),
        sa.Column("return_uri", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.Column("last_modified_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        "oidc_client_by_client_id", "oidc_client", ["client_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("oidc_client_by_client_id", table_name="oidc_client")
    op.drop_table("oidc_client")
    # ### end Alembic commands ###
